- ros_topic_name: "/clock"
  gz_topic_name: "/world/default/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/rotors/command/motor_speed"
  gz_topic_name: "/drone_frame/rotors/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "ignition.msgs.Actuators"
  direction: ROS_TO_GZ

- ros_topic_name: "/thruster_1/force_torque"
  gz_topic_name:  "/world/default/model/drone_frame/link/thruster_1/sensor/thruster_force_torque_1/force_torque"
  ros_type_name:  "geometry_msgs/msg/WrenchStamped"
  gz_type_name:   "gz.msgs.Wrench"
  direction: BIDIRECTIONAL

- ros_topic_name: "/thruster_2/force_torque"
  gz_topic_name:  "/world/default/model/drone_frame/link/thruster_2/sensor/thruster_force_torque_2/force_torque"
  ros_type_name:  "geometry_msgs/msg/WrenchStamped"
  gz_type_name:   "gz.msgs.Wrench"
  direction: BIDIRECTIONAL

- ros_topic_name: "/thruster_3/force_torque"
  gz_topic_name:  "/world/default/model/drone_frame/link/thruster_3/sensor/thruster_force_torque_3/force_torque"
  ros_type_name:  "geometry_msgs/msg/WrenchStamped"
  gz_type_name:   "gz.msgs.Wrench"
  direction: BIDIRECTIONAL

- ros_topic_name: "/thruster_4/force_torque"
  gz_topic_name:  "/world/default/model/drone_frame/link/thruster_4/sensor/thruster_force_torque_4/force_torque"
  ros_type_name:  "geometry_msgs/msg/WrenchStamped"
  gz_type_name:   "gz.msgs.Wrench"
  direction: BIDIRECTIONAL

- ros_topic_name: "/thruster_5/force_torque"
  gz_topic_name:  "/world/default/model/drone_frame/link/thruster_5/sensor/thruster_force_torque_5/force_torque"
  ros_type_name:  "geometry_msgs/msg/WrenchStamped"
  gz_type_name:   "gz.msgs.Wrench"
  direction: BIDIRECTIONAL

- ros_topic_name: "/thruster_6/force_torque"
  gz_topic_name:  "/world/default/model/drone_frame/link/thruster_6/sensor/thruster_force_torque_6/force_torque"
  ros_type_name:  "geometry_msgs/msg/WrenchStamped"
  gz_type_name:   "gz.msgs.Wrench"
  direction: BIDIRECTIONAL

- ros_topic_name: "/thruster_7/force_torque"
  gz_topic_name:  "/world/default/model/drone_frame/link/thruster_7/sensor/thruster_force_torque_7/force_torque"
  ros_type_name:  "geometry_msgs/msg/WrenchStamped"
  gz_type_name:   "gz.msgs.Wrench"
  direction: BIDIRECTIONAL

- ros_topic_name: "/thruster_8/force_torque"
  gz_topic_name:  "/world/default/model/drone_frame/link/thruster_8/sensor/thruster_force_torque_8/force_torque"
  ros_type_name:  "geometry_msgs/msg/WrenchStamped"
  gz_type_name:   "gz.msgs.Wrench"
  direction: BIDIRECTIONAL
